const notes = [
    {id: 1, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2001'},

    {id: 2, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2002'},

    {id: 3, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2003'},

    {id: 4, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2004'},

    {id: 5, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2005'},

    {id: 6, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2006'},

    {id: 7, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2007'},

    {id: 8, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2008'},

    {id: 9, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2009'},

    {id: 10, title: 'Pariatur ullamco velit occaecat aliqua' , details:'sunt ad amet et exercitation adipisicing.Mollit exercitation quis nulla dolore eu ut eu nisi eu magna eu eiusmod. Minim minim incididunt nostrud eiusmod amet nisi. Consequat proident non sint incididunt cupidatat fugiat ex pariatur occaecat. Cillum qui enim enim aute eiusmod anim incididunt culpa. In non labore ex amet ut incididunt sit incididunt ea ea. Enim qui veniam proident non anim occaecat labore voluptate enim ea voluptate laboris est est. Eiusmod in culpa sunt voluptate minim elit Lorem consectetur sint mollit duis dolor exercitation.', date: '08, aug 2010'},

]
export default notes;